version: 2.1

jobs:
  test:
    docker:
      - image: docker
    parameters:
      path:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            cd << parameters.path >>
            docker build -t redmica .
            docker run -d -p 3000:3000 redmica
            apt update
            apt install -y curl
            curl http://localhost:3000 | grep redmine; echo $?
            docker ps -a

workflows:
  workflow:
    jobs:
      - test:
          matrix:
            parameters:
              path: ['1.0.2', '1.0.2/alpine', '1.0.2/passenger', '1.1.0', '1.1.0/alpine', '1.1.0/passenger', '1.1.1', '1.1.1/alpine', '1.1.1/passenger', '1.2.0', '1.2.0/alpine', '1.2.0/passenger', '1.2.1', '1.2.1/alpine', '1.2.1/passenger', '1.2.2', '1.2.2/alpine', '1.2.2/passenger', ]